### PR TITLE
Rabbitmq admin

### PR DESCRIPTION
**Pull request by mattmb**
* Allow enabling the management interface from pillar.

### CODE REVIEW

**Comment by milosgajdos83** [comment]
Is there no USER/PASSWD int this any more ?

**Comment by mikepea** [comment]
@mattmb port 8080 is very commonplace. I'd recommend picking a less standard port for the default and allowing it to be overridable in pillar.

**Comment by mikepea** [comment]
Also, make the firewall opening optional - so that the management interface can only be accessed locally.

**Comment by mattmb** [comment]
@mikepea I picked 8080 because it's accessible from here. What are you thinking re the firewall e.g. maybe:
```
rabbitmq:
  management:
    firewall: open
```
@milosgajdos83 we haven't added user/passwd stuff here but I'd like to add it in a separate PR.

**Comment by mattmb** [comment]
I should put the port in the pillar really. In fact I will.

**Comment by mattmb** [comment]
@mikepea made the changes we discussed. :-)

**Comment by mikepea** [comment]
LGTM

**Pull request merged**
